const cardGrid=document.getElementById("cardGrid"),sectionLabel=document.getElementById("sectionLabel"),emptyMsg=document.getElementById("emptyMsg"),modalOverlay=document.getElementById("modalOverlay"),modalBox=document.getElementById("modalBox"),mainContent=document.getElementById("mainContent"),specialPage=document.getElementById("specialPage"),filterBar=document.getElementById("filterBar");
let allPosts=[],currentTab="all",currentCat="ALL",currentAgency="",currentDays="7",currentSearch="",latestDate=new Date();
async function loadAllPosts(){try{const r=await fetch("./data/manifest.json"),f=await r.json(),d=await Promise.all(f.map(x=>fetch(`./data/${x}`).then(r=>r.json()).catch(()=>({posts:[]}))));allPosts=d.flatMap(day=>day.posts.map(p=>({...p,date:day.date}))).sort((a,b)=>new Date(b.published_at||b.date)-new Date(a.published_at||a.date));if(allPosts.length>0){latestDate=new Date(allPosts[0].published_at||allPosts[0].date);latestDate.setHours(23,59,59,999)}populateAgencies();updateStats();renderCards()}catch(e){sectionLabel.textContent="ไม่สามารถโหลดข้อมูลได้";console.error(e)}}
function populateAgencies(){const a=[...new Set(allPosts.map(p=>p.agency).filter(Boolean))].sort(),s=document.getElementById("agencyFilter");s.innerHTML='<option value="">ทุกหน่วยงาน</option>';a.forEach(x=>{s.innerHTML+=`<option value="${x}">${x}</option>`})}
function updateStats(filtered){if(!filtered)filtered=getFiltered();const bd=filtered.filter(p=>p.urgency==="high"||p.bd_opportunity).length,ag=new Set(filtered.map(p=>p.agency)).size;document.getElementById("statTotal").textContent=`📰 ${filtered.length} ข่าว`;document.getElementById("statAgencies").textContent=`🏢 ${ag} หน่วยงาน`;document.getElementById("statBD").textContent=`🟢 ${bd} โอกาส BD`}
function mapCat(p){const c=(p.topic||"").toUpperCase();if(c.includes("การเงิน")||c.includes("เศรษฐกิจ")||c.includes("การลงทุน"))return"ECONOMY";if(c.includes("นโยบาย")||c.includes("กฎหมาย"))return"POLICY";if(c.includes("การเมือง"))return"POLITICS";if(c.includes("พลังงาน"))return"ENERGY";if(c.includes("ดิจิทัล")||c.includes("ไซเบอร์")||c.includes("เทคโนโลยี"))return"DIGITAL";if(c.includes("สาธารณสุข")||c.includes("สุขภาพ"))return"HEALTH";if(c.includes("คมนาคม")||c.includes("อุตสาหกรรม")||c.includes("โครงสร้าง"))return"INFRA";if(c.includes("การค้า")||c.includes("ท่องเที่ยว")||c.includes("พาณิชย์"))return"TRADE";if(c.includes("ความมั่นคง")||c.includes("กลาโหม")||c.includes("ต่างประเทศ"))return"POLICY";if(c.includes("แรงงาน")||c.includes("การจ้างงาน"))return"TRADE";return"POLICY"}
function getFiltered(){let f=[...allPosts];if(currentTab==="bd")f=f.filter(p=>p.urgency==="high"||p.bd_opportunity);else if(currentTab==="policy")f=f.filter(p=>["POLICY","LAW"].includes(mapCat(p)));else if(currentTab==="economy")f=f.filter(p=>mapCat(p)==="ECONOMY"||mapCat(p)==="ENERGY");if(currentCat!=="ALL")f=f.filter(p=>mapCat(p)===currentCat);if(currentAgency)f=f.filter(p=>(p.agency||"").includes(currentAgency));if(currentDays!=="all"){const ref=latestDate;f=f.filter(p=>{const d=new Date(p.published_at||p.date);return(ref-d)/(1e3*60*60*24)<=Number(currentDays)})}if(currentSearch){const q=currentSearch.toLowerCase();f=f.filter(p=>(p.title||"").toLowerCase().includes(q)||(p.content||"").toLowerCase().includes(q)||(p.agency||"").toLowerCase().includes(q)||(p.tags||[]).some(t=>t.toLowerCase().includes(q)))}return f}
function renderCards(){const posts=getFiltered();updateStats(posts);sectionLabel.textContent=`${posts.length} ข่าว`;emptyMsg.style.display=posts.length?"none":"block";cardGrid.innerHTML=posts.map((p,i)=>{const cat=mapCat(p),tags=(p.tags||[]).slice(0,3);return`<div class="news-card priority-${p.priority||'B'}" onclick="openModal(${i})"><div class="card-top"><span class="cat-badge cat-${cat}">${p.topic||cat}</span><span class="agency-tag">${p.agency||''}</span>${p.bd_opportunity?'<span class="bd-badge">🟢 BD</span>':''}<span class="date-tag">${p.date||''}</span></div><div class="card-headline">${p.title||''}</div><div class="card-summary">${(p.content||'').substring(0,200)}...</div>${tags.length?`<div class="card-highlights">${tags.map(t=>`<span class="hl-chip">${t}</span>`).join('')}</div>`:''}<div class="card-footer"><a class="src-link" href="${p.source_url||'#'}" target="_blank" onclick="event.stopPropagation()">🔗 แหล่งข่าว</a></div></div>`}).join("")}
function openModal(idx){const posts=getFiltered(),p=posts[idx];if(!p)return;modalBox.innerHTML=`<button class="modal-close" onclick="closeModal()">✕</button><div class="card-top" style="margin-bottom:10px"><span class="cat-badge cat-${mapCat(p)}">${p.topic||''}</span><span class="agency-tag">${p.agency||''}</span></div><div class="modal-headline">${p.title||''}</div><div class="modal-meta">${p.date||''} · ${p.category_label||''} · Priority ${p.priority||'B'}</div><div class="modal-body">${p.content||''}</div>${p.bd_opportunity?`<div class="modal-section"><h4>💡 โอกาสทางธุรกิจ</h4><p>${p.bd_opportunity}</p></div>`:''}<a class="modal-link" href="${p.source_url||'#'}" target="_blank">🔗 ดูแหล่งข้อมูลต้นฉบับ</a>`;modalOverlay.classList.add("open");document.body.style.overflow="hidden"}
function closeModal(){modalOverlay.classList.remove("open");document.body.style.overflow=""}
document.querySelectorAll(".tab-btn").forEach(b=>{b.addEventListener("click",()=>{document.querySelectorAll(".tab-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");currentTab=b.dataset.tab;if(currentTab==="special"){mainContent.style.display="none";filterBar.style.display="none";specialPage.classList.add("active");renderSpecial("proc")}else{mainContent.style.display="";filterBar.style.display="";specialPage.classList.remove("active");renderCards()}})});
document.querySelectorAll(".filter-btn").forEach(b=>{b.addEventListener("click",()=>{document.querySelectorAll(".filter-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");currentCat=b.dataset.cat;renderCards()})});
document.getElementById("agencyFilter").addEventListener("change",e=>{currentAgency=e.target.value;renderCards()});
document.getElementById("daysFilter").addEventListener("change",e=>{currentDays=e.target.value;renderCards()});
document.getElementById("searchInput").addEventListener("input",e=>{currentSearch=e.target.value;renderCards()});
modalOverlay.addEventListener("click",e=>{if(e.target===modalOverlay)closeModal()});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
document.querySelectorAll(".special-tab-btn").forEach(b=>{b.addEventListener("click",()=>{document.querySelectorAll(".special-tab-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderSpecial(b.dataset.stab)})});
function renderSpecial(tab){let posts=[];if(tab==="proc")posts=allPosts.filter(p=>(p.tags||[]).some(t=>/จัดซื้อ|tender|e-GP|ประกวดราคา/i.test(t))||p.bd_opportunity);else if(tab==="tax")posts=allPosts.filter(p=>(p.tags||[]).some(t=>/ภาษี|สรรพากร|tax/i.test(t)));else if(tab==="labor")posts=allPosts.filter(p=>(p.tags||[]).some(t=>/แรงงาน|ประกันสังคม|labor/i.test(t)));const c=document.getElementById("specialContent");if(!posts.length){c.innerHTML='<div class="empty-msg">ไม่พบข่าวในหมวดนี้</div>';return}c.innerHTML=`<div class="card-grid" style="margin-top:16px">${posts.map(p=>`<div class="news-card priority-${p.priority||'B'}"><div class="card-top"><span class="cat-badge cat-${mapCat(p)}">${p.topic||''}</span><span class="agency-tag">${p.agency||''}</span></div><div class="card-headline">${p.title||''}</div><div class="card-summary">${(p.content||'').substring(0,150)}...</div></div>`).join("")}</div>`}
loadAllPosts();
